set-option -g status on
set-option -g status-interval 2
#set-option -g status-utf8 on
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
set-option -g status-left "#(~/Env/tmux/tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/Env/tmux/tmux-powerline/powerline.sh right)"

set-window-option -g window-status-current-format "#[fg=colour235, bg=colour27]⮀#[fg=colour255, bg=colour27] #I ⮁ #W #[fg=colour27, bg=colour235]⮀"
bind C-[ run '~/Env/tmux/tmux-powerline/mute_powerline.sh left'      # Mute left statusbar.
bind C-] run '~/Env/tmux/tmux-powerline/mute_powerline.sh right'     # Mute right statusbar.

set -g default-terminal "screen-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix
set-option -g status-bg colour235 #base02
set-option -g status-fg yellow #yellow

# 在窗格边框顶部显示当前工作目录名
set -g pane-border-status top
set -g pane-border-format '#[fg=green]#{pane_index}:#(basename #{pane_current_path})#[default]'

# 窗格边框样式
set -g pane-border-style fg=colour240
set -g pane-active-border-style fg=green

# 当前窗口高亮样式
set-window-option -g window-status-current-style bg=colour27,fg=colour255,bold
# 非当前窗口样式
set-window-option -g window-status-style bg=colour235,fg=colour250
